networks:
  my_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: api
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${URL}
      SPRING_DATASOURCE_USERNAME: ${USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq  # 추가
    networks:
      - my_network
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.prod.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    environment:
      - TZ=Asia/Seoul