services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol
      - "15672:15672"     # 관리 UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest     # 기본 계정
      RABBITMQ_DEFAULT_PASS: guest     # 기본 비밀번호
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
