payment:
  key: ${PAYMENT_API_SECRET}
store:
  key: ${STORE_KEY}
channel:
  key: ${CHANNEL_KEY_DEV}
logging:
  level:
    org.springframework.security: DEBUG
#    io.netty: DEBUG
#    org.springframework.web.reactive.function.client: DEBUG
#    web: debug
spring:
  config:
    import: optional:file:.env[.properties]
  flyway:
    baseline-on-migrate: true
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${CLIENT_DEV_ID2}
            client-secret: ${CLIENT_DEV_SECRET2}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - talk_message

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

