jwt:
  secret: ${JWT_SECRET}

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include: secret
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

server:
  tomcat:
    mbeanregistry:
      enabled: true