logging:
  level:
    io.netty: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    web: debug

spring:
  jpa:
    show-sql: true
    generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379
