spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include: secret
    active: production

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

